POST http://localhost:3000/user/signin
Content-Type: application/json

{
    "login": "daniil",
    "password": "1234"
}

###

GET  http://localhost:3000/todos/?id=046a04b5-f036-4ae0-a07b-701d95fab325
Bearer: eyJhbGciOiJIUzI1NiJ9.eyJpZCI6ImViZWZkODY3LTBlYWItNDM5OC1hNTY4LWYzMzdhODMyZjBlZCIsIm5hbWUiOiJkYW5paWwiLCJwYXNzd29yZCI6IiQyYiQxMCR3aC5rUm5penpNdTBBd3ltUGVNSXhPRlp2bFpUYzB4aWNkbVR2czF2SmlYUml2aFNMUjdzUyJ9.K4P_loa9pXMbUFrdvpbhwqJSlwwHtOiMWcSADtuGbDU

{

}

### 
POST http://localhost:3000/user/restore
Bearer: eyJhbGciOiJIUzI1NiJ9.eyJpZCI6ImViZWZkODY3LTBlYWItNDM5OC1hNTY4LWYzMzdhODMyZjBlZCIsIm5hbWUiOiJkYW5paWwiLCJwYXNzd29yZCI6IiQyYiQxMCR3aC5rUm5penpNdTBBd3ltUGVNSXhPRlp2bFpUYzB4aWNkbVR2czF2SmlYUml2aFNMUjdzUyJ9.K4P_loa9pXMbUFrdvpbhwqJSlwwHtOiMWcSADtuGbDU

